### ISSUE TITLE
Handlers after append HTML not working

### ISSUE THREAD

**Issue by mihmul83** [franciscop/umbrella#100]
HI, i draw html elements using .append, as expample 
`u('.someclass').on('click',function(){console.log('ok')});
var str = '<span class="someclass">SPaN</span>'
u(someelement).append(str);`

click event will not working
but if i change place handler and .append - it will be work

in jquery we have 
`$(document).on('click','.someclass',handler)`
that work good with dinamyc content.
How can i get this in umbrella?

**Comment by franciscop** [comment]
This should work as well in Umbrella:

```js
u(document).on('click', '.someclass', handler);
```

Please let me know if it doesn't work.

**Comment by NetLancer** [comment]
Nice!
I just wonder why so many projects (CMS, E-commerce platforms ..) still use $bulky jquery while (as far as i see) mostly what they do basically match umbrella features?
While in some projects using plain js with bigger code amount, it still seems the code could be significantly reduced (=> more readable) if umbrella used

**Comment by mihmul83** [comment]
Sorry, i was wrong - it will work perfectly with Unbrella
