### ISSUE TITLE
alternatives to not existing .css() method?

### ISSUE THREAD

**Issue by gnadelwartz** [franciscop/umbrella#101]
I'm trying to port an userscript from jquery to umbrella.
In most cases this is very easy because of the similarities between both.

Im now looking for an alternative to .css() method.

I general I avoid using .css() to set CSS properties because I think this is better handled by pur CSS rules, but where .css() is good for is getting the effective CSS property. How ca I do this with umbrella?

I tried `u('#myid').node[0].style.getPropertyValue('top')` but this seems not to be correct.

Any advise?

**Comment by gnadelwartz** [comment]
my current solution is

```
// alternative for jquery .css() get method
// https://www.htmlgoodies.com/html5/css/referencing-css3-properties-using-javascript.html#fbid=b2-TgWC-yGY
function getStyle(oElm, css3Prop){
    // FF, Chrome etc.
    if(window.getComputedStyle){
        try { return getComputedStyle(oElm).getPropertyValue(css3Prop); }
        catch (e) {}
    } else {
        // IE
        if (oElm.currentStyle){
            try { return oElm.currentStyle[css3Prop]; }
            catch (e) {}
        }
    }
    return "";
}

}
 
//usage examples
getStyle(u('.myClass').nodes[n], "border-radius");
getStyle(getElementsByClassName('.myClass')[n], "border-radius");
getStyle(getElementById('myID'), "border-radius");

```
see: https://www.htmlgoodies.com/html5/css/referencing-css3-properties-using-javascript.html#fbid=b2-TgWC-yGY

**Comment by franciscop** [comment]
A great alternative if you really like it creating a small internal plugin for Umbrella in your own code that you can then include in your project. Untested, but it comes from the [`attr()` method](https://github.com/franciscop/umbrella/blob/master/src/plugins/attr/attr.js). You'd have to define your `setStyle` and `getStyle`, but I think the `getStyle` should be compatible with your code above:

```js
u.prototype.css = function (name, value) {

  // Convert it into a plain object if it is not
  if (value !== undefined) {
    var nm = name;
    name = {};
    name[nm] = value;
  }

  if (typeof name === 'object') {
    // Set the value of each one, for each of the { prop: value } pairs
    return this.each(function (node) {
      for (var key in name) {
        setStyle(node, key, name[key]);
      }
    });
  }

  // Return the style of the first one
  return this.length ? getStyle(this.first(), name) : undefined;
};
```

Then to use it like in jQuery:

```js
// Find out the border radius of the first element
u('a').css('border-radius');

// Set the border radius of all elements:
u('a').css('border-radius', '10px');

// Also set the border of all elements, but as an object:
u('a').css({ 'border': '1px solid red' });
```

**Comment by franciscop** [comment]
Note: I just made a release, `2.10.0`, to make it easier to use the code above. If you are using a previous version the `this.pairs()` won't work, make sure to upgrade first.

**Comment by gnadelwartz** [comment]
will this relaease automaticially pulled if I use the link https://unpkg.com/umbrellajs

**Comment by franciscop** [comment]
Yes, a version with `.pairs()` will automatically be pulled from there.

**Comment by gnadelwartz** [comment]
how can I create code section with colored syntax, like in your comment?
