### ISSUE TITLE
porting howto / tips availible?

### ISSUE THREAD

**Issue by gnadelwartz** [franciscop/umbrella#102]
Similar to my question about portimg from jquery to umbrella I would like to aks if there exists a porting howto or tips sqction somwhere?

google did not help me to find something like this.

If its not existing today you may consider to setup somthing like this for umbrella and allow people to share their knowleded there. As I also had some finding I can provide there for newbies

**Comment by gnadelwartz** [comment]
so one topic of interesser for user new to umbrella may be:

**.replaceWith() does not exist**

this should be very simple, use the umbrella `.replace()` method instead :-)
even this may confuse you because of the native javascript .replace() method it works ...

**Comment by gnadelwartz** [comment]
one more:

**u(this) does not work like in jquery**

in contrast to jquery does  not change the scope of the javascript `this` property. But its easy to emulate it.

simply modify jquery .each() loops:

```
$('.myremove'.each(function () {
    ...
    $(this).dosomething();
    ...
});

```
to someting like:

```
u('.myclass'.each(function (that) {
    ...
    u(that).dosomething();
    ...
});
```
umbrella provides the actually processed node as first argument to the called function, [see also .each()](https://umbrellajs.com/documentation#each). you can use any varibale name instead of `that`, but I like it because its easy to remember for jquery programmers :-)

**Comment by gnadelwartz** [comment]
porting from jquery to umbrella is rally easy and it helps me also to fix some otherwhise unnoticed bug in the script :-)

**Comment by gnadelwartz** [comment]
**.first() returns native DOM element**

in jquery `.first()` returns a jquery object, but umbrella it returns the native DOM object. this has pro pro and con:

- pro: you can use faster native javascript DOM manipulation
- con: you can't chain an other umbrella method like in jquery
- con: be careful to select the correct DOM method!

example: how to get inner html:

```
$('.myclass').first().html();

// direct access to DOM innerHTML 
u('.myclass').first().innerHTML;
```
example: how to add html before element:

```
$('.myclass').first().before('<div>this is inserted before</div>');

// use of .insertAdjacentHTML(), native DOM method  .before() requires DOM node!
u('.myclass').first().insertAdjacentHTML('beforebegin', '<div>this is inserted before</div>');

// wrong: works not as you may expect!
// insert TEXT => "&lt;div&gt,this is inserted before&lt;/div&gt,"
$('.myclass').first().before('<div>this is inserted before</div>');

```
for append, prepend etc. see  [.insertAdjacentHTML() ](https://developer.mozilla.org/docs/Web/API/Element/insertAdjacentHTML)

**Comment by franciscop** [comment]
Hi @gnadelwartz , thank you for everything said here. There is nothing written about how to migrate from jQuery, and as you commented there are some smaller differences. For instance, the looping is purposefully like this to follow the native elements API closer. With Arrow Functions:

```js
// Native and Umbrella
['a', 'b', 'c'].forEach(item => console.log(item));
u('a').each(item => console.log(item));

// jQuery
$('a').each((i, item) => console.log(item));
```

For the `.first()` example you can just wrap the whole thing into another `u()` and use `.before()` conveniently.

Please feel free to put these things into a `.md` and put it into the root of the project and then link it either through the README.md or the documentation (or both).

**Comment by gnadelwartz** [comment]
I'll provide an jquery_porting.md as a PR if I'm finished with porting of my script.

nevertheless, can you habe a look at my .css() issue? because you may have an advise how to implent my current solution as an umbrella extension ...
