### ISSUE TITLE
how to break out of .each()?

### ISSUE THREAD

**Issue by gnadelwartz** [franciscop/umbrella#103]
in jquery you can `return false;` to stop the iteration of an `.each()` loop
this seems to work different in umbrella, the remaining iterations are done instead of skipped

```js
u('article').each(function (that,i) {
     dosometing(that);
     if (i==5) return false;
})
```

You can workaound with something like this, but ist a waste of CPU cycles:

```js
var skip=false;
u('article').each(function (that,i) {
     if(skip) return;
     dosometing(that);
     if (i==5)  { skip=true; return; }
})
```

**Comment by franciscop** [comment]
It will depend on the situation a lot. For instance, you could `filter()` before doing the each. For this situation:

```js
u('article').filter((article, i) => i < 5).each(function (that,i) {
  dosometing(that);
});
```

Or just:

```js
u('article').each(function (that,i) {
  if (i >= 5) return;
  dosometing(that);
});
```

But of course that would depend on the specific situation. I prefer strongly filtering before doing the operations though.
