### ISSUE TITLE
.text() returns the same result as .html()?

### ISSUE THREAD

**Issue by gnadelwartz** [franciscop/umbrella#104]
In jquery `.text()` strips out all html tags and returns only the text inside html tags.
current umbrella seems to return with `.text()` the same content as `.html()`

```
$('#lastchange').text() // returns 'vor 42 m eingestellt vor 42 m'
u('#lastchange').text() // returns '<span class="ico space--r-1 ico--type-tag-greyShade"></span><span class="hide--fromW3">vor 42 m</span><span class="hide--toW3">eingestellt vor 42 m</span>'
u('#lastchange').html() // returns '<span class="ico space--r-1 ico--type-tag-greyShade"></span><span class="hide--fromW3">vor 42 m</span><span class="hide--toW3">eingestellt vor 42 m</span>'
```
a simple workaround is to strip all tags returned from `.html()`, but then there may no neeed for `.text()`

`u('#lastchange').html().replace(/<.*?>/gi, ' ');`

**Comment by gnadelwartz** [comment]
Forget about it, is was looking at the wrong statement! Sorry

**Comment by franciscop** [comment]
The method `ajax()` is being deprecated for the standard `fetch()`. Please see the relevant issue and let me know if you have anything against it: httpsthub.com/franciscop/umbrella/issues/124
