### ISSUE TITLE
does $.ready() equivalent exist? 

### ISSUE THREAD

**Issue by gnadelwartz** [franciscop/umbrella#111]
will something like `u(document).on("DOMContentLoaded", callback)` work ???
or do I have to use: `document.addEventListener("DOMContentLoaded", callback)`

**Comment by franciscop** [comment]
This has been discussed here and there are three proposed solutions: https://github.com/franciscop/umbrella/issues/86

Please comment on that issue if you have any problem usimg any of them and I'll be happy to help.
