### ISSUE TITLE
Cross-domain GET request fails due to "X-Requested-With" header

### ISSUE THREAD

**Issue by renehamburger** [franciscop/umbrella#112]
The request `ajax('https://rawgit.com/franciscop/umbrella/master/README.md'` fails with the error message 'Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response.' in Chrome. See [this JSFiddle](https://jsfiddle.net/rene/mwpcqddj/184/).

nanoajax only adds this header [only for 'POST' requests](https://github.com/yanatan16/nanoajax/blob/master/index.js#L75), so I'd suggest you do the same. I'll create a PR along those lines in a moment, if that's OK?

**Comment by franciscop** [comment]
Hi @renehamburger,

This would decrease the security by allowing CSRF attacks: [see this SO answer](https://stackoverflow.com/questions/17478731/whats-the-point-of-the-x-requested-with-header).

Not only that, but we do want the headers to be sent in your own domain so you can identify properly what is AJAX and what is not.

Please feel free to use the `fetch()` native API or polyfill your code like `u.ajax = ...`, but adding this PR would be a matter of preference/compatibility, with this change being a win for some and a lose for others. And I strongly prefer not breaking current users workflow.

**Comment by franciscop** [comment]
Umbrella's `ajax()` is being deprecated in favor of the native `fetch()`, please see relevant issue and feel free to share your opinion: https://github.com/franciscop/umbrella/issues/124
