### ISSUE TITLE
How to return complete html string from list of nodes?

### ISSUE THREAD

**Issue by smcllns** [franciscop/umbrella#121]
I think umbrella probably handles this, but I can't find the way. After using umbrella to select a array of nodes, how should I convert a list of nodes back to a complete html string?

## Example:

1. Let's say we have:

```html
<ul>
<li>foo</li>
<li>bar</li>
</ul>
```

2. I select the elements and do some transformation.

```js
u( li ).each(( node, i ) => u( node ).text( 'baz' + i ))
```

3. Now I want to update the DOM with all the new items to create:

```html
<ul>
<li>baz0</li>
<li>baz1</li>
</ul>
```

## Issues

- If I use `.html()` on an umbrella list, it just returns the html for the first node in the list
- If I use `.html()` on each umbrella item, I get the innerHTML and often need the outer.
- I achieve what I want with: 
```js
ul.innerHTML = myUmbrellaObject.nodes.reduce(( htmlString, node ) => htmlString += node.outerHTML, '' )
```

Have I missed something, or is this the expected behavior and right way to handle this? Thanks!

**Comment by franciscop** [comment]
> closed by accident

**Comment by franciscop** [comment]
To get the outer html you could use the native [`.outerHtml`](https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML):

```js
u('li').each(node => {
  var contents = node.outerHtml;
  // ...
});
```

But could you be more specific about what you want please? Is this snippet like yours better?

```js
u( li ).each(( node, i ) => u( node ).text( u( node ).text() + i ))
```

**Comment by franciscop** [comment]
Just in case, check out also the `.append()` method since you seem to want to just append a bit: https://umbrellajs.com/documentation#append

**Comment by franciscop** [comment]
Ah sure, what about just the inner html of the parent then? It should be fairly the same:

```js
u('ul').html();  // => '<li>One</li><li>Two</li>'
```

If you want to somehow manipulate them (as it seems), there is no way to get the outer html of them all in a single call.

I'd suggest this which would be quite more simple than reducing it from your initial comment example:

```js
u('li').nodes.map(node => node.outerHTML).join('');  // => '<li>One</li><li>Two</li>'
```

Or even set it up in a temporary `<ul>` and get that html:

```js
u('<ul>').append(u('li')).html(); // => '<li>One</li><li>Two</li>'
```

Finally, if you are going to be doing this very often across your code, you can just define a plugin and reuse it:

```js
// Define the plugin to return all of the nodes outerHTML together
u.prototype.htmlToString = function () {
  return this.nodes.map(node => node.outerHTML).join('');
};

// Use it in your codebase:
u('li').htmlToString();
```

See them all [**working in a JSFiddle**](https://jsfiddle.net/franciscop/zekbah0n/4/).
