### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by franciscop** [franciscop/umbrella#124]
Hi everyone, I am thinking about publishing a 3.0 with these breaking changes:

- Remove `ajax()`. Since the [DOM API `fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) is almost the same (it's better actually!) and [the awesome https://polyfill.io/](https://polyfill.io/) already covers for older browsers, `ajax()` is totally pointless nowadays.
- Remove the method `.ajax()`, this is a small helper that I have never ever used and is strongly tied to the former.

In exchange of these, the library would decrease from 3.5kb to 2.5kb, an almost 30% decrease in size. Tiny enough to embed it anywhere easily. I would remove `.serialize()` for the [DOM API `FormData()`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) if the latter was a bit easier to use.

Anyone uses either the request call `ajax()` or the handler `.ajax()` heavily? For the latter I could provide in the docs a replacement using `fetch()` but would not bundle that into the main library.

Note: I've already done this in dev, removing two plugins is trivial. Just wondering if there's anyone strongly opposing this and why.

**Comment by tapir** [comment]
sounds good to me. lighter the better. I actually switched to fetch() myself :+1:
