### ISSUE TITLE
Ajax suddenly missing (unable to find documentation of this change)

### ISSUE THREAD

**Issue by Asuza** [franciscop/umbrella#125]
I assume `ajax` was removed during some new release, but I couldn't find change logs for it anywhere. Changing my application to use `fetch` instead is a big change.

Is there a document somewhere mentioning changes in the API, deprecated features, etc?

**Comment by leeoniya** [comment]
https://github.com/franciscop/umbrella/blob/master/migrate-2-to-3.md

**Comment by franciscop** [comment]
@leeoniya link is the correct one, see also the issue: https://github.com/franciscop/umbrella/issues/124

The API of native `fetch()` and umbrella's `ajax` is very similar, and in the linked document it explains how to keep using the old `ajax()`. In the 3.0 there are only removals as well.

Where did you expect to see the changes? In the README there is also a link saying "Migrate from 2.0 to 3.0". Would a Changelog.md help?

**Comment by leeoniya** [comment]
changelog.md would help and/or notes in the Releases tab

**Comment by franciscop** [comment]
Updated release: https://github.com/franciscop/umbrella/releases/tag/3.0.0
