### ISSUE TITLE
Scrolling on the docs page is annoyingly slow

### ISSUE THREAD

**Issue by limonte** [franciscop/umbrella#127]
Right now, I'm able to go to the kitchen, grab a coffee and come back to the working place while scrolling is happening.

Is is possible to descrease the waiting time by increasing the scrolling speed?

![umbrellajs](https://user-images.githubusercontent.com/6059356/44670947-c8444380-aa2c-11e8-99c8-bfc927f2481f.gif)

**Comment by franciscop** [comment]
No, you can open a bug report to your browser since it's using the default browser method:

```js
// scroll.js
u.prototype.scroll = function () {
  this.first().scrollIntoView({ behavior: 'smooth' });
  return this;
};
```

If you want to use `.scroll()`, you can overwrite the behavior:

```js
// Write this somewhere in your code
u.prototype.scroll = function () {
  this.first().scrollIntoView();
  return this;
};
```

Or just do it manually:

```js
u('.my-element').first().scrollIntoView();
```

**Comment by limonte** [comment]
Thanks @franciscop for the prompt reply.

> No, you can open a bug report to your browser

Well, I'm using the default browser on the default OS, so the majority of those who are reading umbrellajs docs experiencing the same poor UX.

To clarify myself, umbrellajs and its scroll method are fine, the docs page is not. It's quite a big document and it takes a lot of time to scroll it all.

I think it would be better to get rid of scrolling at all and to just use ol' good anchors.
