### ISSUE TITLE
How to attach an event listener with the `capture` option?

### ISSUE THREAD

**Issue by limonte** [franciscop/umbrella#128]
From https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

```js
target.addEventListener(type, listener[, options]);
```

![image](https://user-images.githubusercontent.com/6059356/44949889-582a2900-ae43-11e8-8d64-7ae6ef6fe03f.png)

With UmbrellaJS, how can I add an event listener (e.g. `click`) with `capture: true`?

**Comment by franciscop** [comment]
It is not possible and seems rare enough not to be within the scope of Umbrella JS. If you can provide a very clear usercase I would be willing to reconsider, but not as-is.
