### ISSUE TITLE
Help translating a jQuery dependent script to Umbrella

### ISSUE THREAD

**Issue by kaushalmodi** [franciscop/umbrella#130]
Hello,

First of all, I am not a web developer and I don't know JS. So I am asking for help converting a jQuery dependent script to Umbrella, as I want to reduce the weight of my static site.

---

### Script

```js
(function() {
    var $window = $(window);
    if ($window.width() >= 1400) { // Match this number with the min-width CSS rule for .hugotoc
        var $toc = $('#TableOfContents');
        if ($toc.length > 0) {
            function onScroll(){
                var currentScroll = $window.scrollTop();
                var h = $('.content h1, .content h2, .content h3, .content h4, .content h5, .content h6, .h-feed h2');
                var id = "";
                h.each(function (i, e) {
                    e = $(e);
                    if (e.offset().top - 10 <= currentScroll) {
                        id = e.attr('id');
                    }
                });
                var current = $toc.find('a.current');
                if (current.length == 1 && current.eq(0).attr('href') == '#' + id) return true;

                current.each(function (i, e) {
                    $(e).removeClass('current').siblings('ul').hide();
                });
                $toc.find('a[href="#' + id + '"]').parentsUntil('#TableOfContents').each(function (i, e) {
                    $(e).children('a').addClass('current').siblings('ul').show();
                });
            }
            $window.on('scroll', onScroll);
            $(document).ready(function() {
                $toc.find('a').parent('li').find('ul').hide();
                onScroll();
                document.getElementsByClassName('hugotoc')[0].style.display = '';
            });}}})();
```

[Ref][1]

---

If it's possible to convert the above code to use Umbrella, can you please provide equivalent code.

I looked though [documentation][0] (searched for "window") but failed at finding something equivalent to `$(window)`.

[0]: https://umbrellajs.com/documentation
[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/fed3553bdc35472ba6ed7018bd6463a976bd784c/layouts/partials/toc_on_side.html#L6-36

**Comment by franciscop** [comment]
Sorry, but I don't provide this kind of support.

You can always donate to the author(me), but that would not guarantee this kind of support of course (since it's a donation): https://www.paypal.me/franciscopresencia

Or you could hire me for freelancing, but that would be overblown for the scope of this.

**Comment by kaushalmodi** [comment]
Thanks for the reply. I can understand that you cannot give this kind of support to each Tom, Dick and Harry. I thought it wouldn't hurt asking.

I donate to all the FOSS projects I use :) I would do to this one too, but so far I cannot use it. I'll ask for help on other channels.

**Comment by kaushalmodi** [comment]
@franciscop Is it at least possible to translate the above jQuery snippet (ignoring the `ready` fn part) to Umbrella? If so, I can at least start spending time to figure this one out myself.

**Comment by franciscop** [comment]
Seems possible on principle, but since you seem not to know Javascript at all (`window` is the native object) it would probably take a while for you. I'd recommend asking a friend for help or learning the basics of Javascript first. Or try Zepto, it's a drop-in replacement for jQuery.

Tip: check `.size()` from Umbrella docs, seems like you are using quite a few size-related bits.
