### ISSUE TITLE
This lib support Android 4.4+ webview?

### ISSUE THREAD

**Issue by DemonCloud** [franciscop/umbrella#135]
This lib support Android 4.4+ webview?

**Comment by DemonCloud** [comment]
Oh my god..  it not support  $("xxx").off()  empty eventName, 
if eventName not exist, jQuery will remove all this event on delegator root DOM

**Comment by franciscop** [comment]
I haven't tested on 4.4. It used to support fairly old Androids, but I don't know how far back. Please open this site in the browser that you want to check for support:

https://umbrellajs.com/tests

PRs welcome if you found any bug, but remember Umbrella is not a jQuery clone, it is an alternative :)
