### ISSUE TITLE
querySelectorAll() performance

### ISSUE THREAD

**Issue by mjau-mjau** [franciscop/umbrella#136]
Hi! Ditching jQuery in favor of vanilla, I was looking for a smaller library to help with DOM manipulation, and although "selector performance" is arbitrary and often irrelevant, I was disappointed to find that `u()` doesn't use `getElementById()`, `getElementsByClassName()` or `getElementsByTagName()`, which are substantially faster than `querySelectorAll()`. 

I did a quick and shady selector performance test loop:
https://codepen.io/anon/pen/XQNbrG?editors=1011
**getElementById('id'):** 51.302001953125ms
**$('#id'):** 101.3662109375ms
**u(document.getElementById('id')):** 117.32080078125ms
**u('#id'):** 425.364990234375ms

There is a better test below with similar results:
https://www.measurethat.net/Benchmarks/Show/4349/14/vanilla-vs-cash-vs-umbrella-vs-bliss-vs-zepto-vs-jquery

What's perhaps most interesting, is that `u(document.getElementById('id'))` is substantially faster than `u('#id')`, which defeats the purpose of using U() as a selector shortcut, and seems not to agree with the umbrella [docs](https://umbrellajs.com/documentation#home):

> You should use u('#demo') instead of u(document.getElementById('demo')), internally it's optimized to do this in a fast way.

Would be cool if one could use u() as an optimally-performant selector, instead of having to avoid it unless strictly necessary. I know we are speaking microscopic differences, but when abandoning jQuery for vanilla performance benefits, it seems like a step forward and a step back.

Couldn't you easily detect single-word "#id", ".class" and "tag" from string in `select.js`, and only resort to querySelectorAll() when required? Functionality-wise, UmbrellaJS looks great! 👌

**Comment by franciscop** [comment]
Oops, sorry I forgot to delete that comment. The browsers are changing all the time the internal working of those selectors; initially `querySelectorAll()` was slower, then they (don't even remember which ones, but I'm pretty sure at least Chrome) made this optimization internally. Seems like this was reverted/deoptimized?

While 10x slower than the native `getElementById()`, if we take a step back and consider that you are selecting 100000 elements at 425ms (or, 0.00425ms/selection) this is still not an issue... IMHO Umbrella is great for the data size, following more vanilla JS and its flexibility, not for raw performance like this.

The [2.x version](https://unpkg.com/umbrellajs@2.10.3/umbrella.min.js) used to use this BTW,.

**Comment by franciscop** [comment]
Please also see: https://github.com/franciscop/umbrella/issues/133
