### ISSUE TITLE
Looking for areas to contribute.

### ISSUE THREAD

**Issue by tanaypratap** [franciscop/umbrella#137]
This library is quite exciting. I am looking for areas to contribute. Kindly create issues or work items I can pick up.

**Comment by franciscop** [comment]
Hi @tanaypratap, thanks!! Unfortunately I consider Umbrella to be feature-complete, but if you find a method that you *really* need or want to implement feel free to open an issue. I could ask for tests or docs, but I am pretty sure there are newer, more used libraries that could get that kind of help :)
