### ISSUE TITLE
Comparison alternatives

### ISSUE THREAD

**Issue by pwFoo** [franciscop/umbrella#84]
Hi,

I found umbrella and it looks nice, but at the moment to much modules / plugins have a jQuery dependency to move away... 👎 

Maybe the comparison table could be interesting (German link...)?
https://nerdkrams.de/6-leichtgewichtige-jquery-alternativen-im-funktionsvergleich/

I played with [Minified.js](http://minifiedjs.com/) which is really nice and a full jQuery replacement looked at the functionalities.

And recently found [kimbo.js](http://kimbojs.com/)

**Comment by franciscop** [comment]
What do you mean? There is no jquery dependency at all, it is just there for testing Umbrella JS speed against jQuery, but of course there is no jQuery in the production code.

**Comment by pwFoo** [comment]
Not  umbrella have jquery dependencies, but many published things (lightboxes, sliders, menu / nav). So it isn't easy to move from jquery to umbrella vor any other framework.

But umbrella - as other alternatives too - is great work!

I would love to see jquery replaced by a smaller solution in the future.

**Comment by franciscop** [comment]
Ah thanks! However it is not a jQuery replacement, for that there are few alternatives like [Zepto.js](http://zeptojs.com/)

Umbrella's goals are to help you with development in a similar way to jQuery, but not to replace it totally.
