### ISSUE TITLE
load/ready event

### ISSUE THREAD

**Issue by flamner** [franciscop/umbrella#86]
How to make load or ready event like in jquery $( document ).ready() ??

**Comment by franciscop** [comment]
Why do you need `$(document).ready()`? There are several possible reasons why people use this, and I'd be able to recommend how to do it better if I know the specific reason.

**Comment by NetLancer** [comment]
I wonder if native 'DOMContentLoaded' looks too frustrating to have it just a little shortened in third part libraries? Thanx for keeping umbrella slim and fast franciscop :)

**Comment by franciscop** [comment]
I agree @NetLancer , but what I mean is that if you load your `<script>`s at the end of your `<body>` you don't need it at all. Otherwise (or in unknowns), you can use [You might not need jQuery example](http://youmightnotneedjquery.com/#ready):

```js
function ready(fn) {
  if (document.readyState != 'loading'){
    fn();
  } else {
    document.addEventListener('DOMContentLoaded', fn);
  }
}
```

**Comment by uxitten** [comment]
```
u.ready= function (fn) {
    if (document.readyState != 'loading'){
      fn();
    } else {
      document.addEventListener('DOMContentLoaded', fn);
    }
};
```

**Comment by franciscop** [comment]
@uxitten 128 vs 111 bytes, so the difference is negligible. Then it all depends on taste, do you prefer working with guard clauses or ternary operations? Does the 84 lines lint properly within your code?

Three alternatives solutions are provided now so I'm closing this.
