### ISSUE TITLE
.create() method

### ISSUE THREAD

**Issue by ubery** [franciscop/umbrella#89]
Method to create DOM Element by passing plain object. It could be internal constructor function or using to pass JSON as a complete element's attributes structure. It's highly useful when creating dom structure without repeating library methods over and over.

`u(parameter, context)` where parameter is selected as element generator, and context is a plain object:
```js
u("<div>", {
  id: "main",
  class: "box",
  title: "click me",
  on: {
    click: e => {} 
  }
},
  u(child1),
  u(child2),
  ...
);
```
Possible children as an array or next arguments. This is a constructor use, but I think it can be also a simple method to set bunch of attributes at once to existing element or newly created.

```js
u("<div>").create({
  ...
})
```

I've got code working like this and could be implemented.

**Comment by franciscop** [comment]
This can be done simply with a string and an append...

```js
u(`<div
  id="main"
  class="box"
  title="click me"
  onclick="click: e => {}"></div>`).append(child1, child2);
```

Of course it depends on what your main objective it is, but it can be done easily in many different ways so I think there is no real point for this.
