### ISSUE TITLE
.append() multiple instances of Umbrella

### ISSUE THREAD

**Issue by ubery** [franciscop/umbrella#90]
There is an error when appending array with instances of Umbrella (all methods based on `adjacent`). They aren't just nodes and `isInPage` with `document.body.contains(a)` doesn't get it.

Documentation clearly states, that it must be an array of nodes, but I think it's next step to full cover manipulation of instance of Umbrella (more than one in this case).

One of the bypass is converting all instances to single array and then passing to `.append()` method. This thought also brings idea of method like `.add()` or something to merge two instances. But it should be solution to work with array of any node, string or Umbrella instance.

**Comment by franciscop** [comment]
Could you share some code with the error, please? Sorry for missing your 2 issues.

**Comment by franciscop** [comment]
Closing it due to inactivity
