### ISSUE TITLE
Slice functionality

### ISSUE THREAD

**Issue by michaeltrilford** [franciscop/umbrella#91]
I'm trying to replicate the slice functionality from jQuery, however I'm struggling a we bit. Does UmbrellaJS support this?

I'm trying to replicate existing functionality where I'm trying to select a certain range of elements, which I can then modify once a certain condition has been met.

**Comment by schelmo** [comment]
you can always work with the internal array:
```javascript
var myElements = u('ul > li');
// get the second and third element
u(myElements.nodes.slice(1, 3))
```

**Comment by franciscop** [comment]
It doesn't have it natively but schelmo answer would work pretty well. You can even do it in one line if you are just prototyping (with a reduced readability in that case):

```js
u(u('ul > li').nodes.slice(1, 3));
```

If you are using this a lot, you could also add it as a plugin to your project:

```js
u.prototype.slice = function(beginning, end){
  this.nodes = this.nodes.slice(beginning, end);
  return this;
};

// Later on:
u('ul > li').slice(1, 3);
```
