### ISSUE TITLE
jshint configuration and dependency are remaining.

### ISSUE THREAD

**Issue by kt3k** [franciscop/umbrella#92]
It seems that the linting is switched to semistandard [here](https://github.com/franciscop/umbrella/commit/3ec20e89373d2d23dd933734c9bec23459a5a45f#diff-35b4a816e0441e6a375cd925af50752c), but jshint dependency and configurations seem still remaining. Is this intentional?

**Comment by franciscop** [comment]
No reason, just didn't clean up properly :+1:

**Comment by franciscop** [comment]
Should be done and published now on [2.9.0](https://github.com/franciscop/umbrella/releases/tag/2.9.0)

**Comment by kt3k** [comment]
Thanks!
