### ISSUE TITLE
Misunderstanding first

### ISSUE THREAD

**Issue by quko8** [franciscop/umbrella#95]
I wanna do something like `u('div').first().on('click', () => {})`
but only way that i see now is a boilerplate code like 
```
const first = u('div.card').first()
    u(first).on('animationend', () => alert('done'))
```

**Comment by franciscop** [comment]
You can get the same behaviour with a smaller syntax like:

```
.filter((el, i) => i == 0).on(...);
```

The time complexity is O(n) instead of O(1), but if this matters you got bigger issues ;)
