### ISSUE TITLE
the ajax seems cannot handle form with get method

### ISSUE THREAD

**Issue by kaala** [franciscop/umbrella#96]
also cannot handle post multipart form data

**Comment by franciscop** [comment]
Could you provide an example please?

[It seems to be working as intended](https://jsfiddle.net/franciscop/5amdp5yf/).

About the multiform TBH I never tried that. I would have to dig deeper about multipart, but AFAIK I never implemented support for that.

**Comment by kaala** [comment]
I edited your example
https://jsfiddle.net/5amdp5yf/3/

There are 2 form, the first one is using umbrella, the second one is plain html
The form data should append to url as query string.

**Comment by franciscop** [comment]
The method `ajax()` is being deprecated for the standard `fetch()`. Please see the relevant issue and let me know if you have anything against it: httpsthub.com/franciscop/umbrella/issues/124
